name: DevSecOps Pipeline

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SAST - npm audit
        run: npm audit --audit-level=high || true

      - name: SCA & Container Scan - Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bkimminich/juice-shop
          severity: HIGH,CRITICAL

      - name: DAST - OWASP ZAP
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: http://localhost:3000
