name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout source code
    - name: Checkout Source Code
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4. SAST - npm audit
    - name: SAST - npm audit
      run: npm audit --audit-level=high || true

    # 5. SCA - Trivy File System Scan
    - name: SCA - Trivy FS Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: HIGH,CRITICAL

    # 6. Build Docker Image
    - name: Build Docker Image
      run: docker build -t juice-shop-devsecops .

    # 7. Run OWASP Juice Shop Container (WAJIB untuk DAST)
    - name: Run OWASP Juice Shop
      run: |
        docker run -d -p 3000:3000 juice-shop-devsecops
        sleep 30

    # 8. Container Security Scan
    - name: Container Scan - Trivy Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: juice-shop-devsecops
        severity: HIGH,CRITICAL

    # 9. DAST - OWASP ZAP Baseline Scan
    - name: DAST - OWASP ZAP
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: http://localhost:3000

